### PR TITLE
halve rewards

### PR DESCRIPTION
**Pull request by zashton**

### CODE REVIEW

**Comment by jondwillis** [comment]
Ideally this should be calculated via the contract instead of hardcoded. 
https://github.com/jondwillis/baoswap-ui/blob/feature/baoswap-2/src/hooks/TVL.ts#L431

**Comment by zashton** [comment]
> Ideally this should be calculated via the contract instead of hardcoded.
> https://github.com/jondwillis/baoswap-ui/blob/feature/baoswap-2/src/hooks/TVL.ts#L431

awesome , looks like you already got a solution, feel free update my PR.

**Comment by Vitalsine85** [comment]
> Ideally this should be calculated via the contract instead of hardcoded.
> https://github.com/jondwillis/baoswap-ui/blob/feature/baoswap-2/src/hooks/TVL.ts#L431

Was this ever implemented?

**Comment by jondwillis** [comment]
> > Ideally this should be calculated via the contract instead of hardcoded.
> > https://github.com/jondwillis/baoswap-ui/blob/feature/baoswap-2/src/hooks/TVL.ts#L431
> 
> Was this ever implemented?

it hasn't been yet

**Pull request closed without merging**
